version: "3.8"

services:
  frontend:
    image: "front-container:dev"
    container_name: front-container-dev
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
      cache_from:
        - "front-container:dev"
    command: npm -Wd run dev
    ports:
      - 3000:3000
    depends_on:
      - backend
    env_file:
      - ./frontend/.env.local
    volumes:
      - ./frontend:/front
      - /front/node_modules

  backend:
    image: "back-container:dev"
    container_name: back-container-dev
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
      cache_from:
        - "back-container:dev"
    ports:
      - 8080:8080
    environment:
      - MONGODB_URI=mongodb://admin-user:admin-password@mongodb:27017/test-database?authSource=admin
    env_file:
      - ./backend/.env
    volumes:
      - ./backend:/app
      - /app/node_modules

  mongodb:
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin-user
      MONGO_INITDB_ROOT_PASSWORD: admin-password
      MONGO_INITDB_DATABASE: test-database
    restart: unless-stopped
    ports:
      - 27017:27017
    volumes:
      - ./db:/data/db

volumes:
  front_build:
  back_build:
