FROM node:18-alpine As builder

WORKDIR /app

COPY package.json package-lock.json ./
RUN npm ci --production

COPY . .

RUN npm run build:prod

FROM node:18-alpine as runner

WORKDIR /app

COPY --from=builder /app/package.json /app/package-lock.json ./
RUN npm ci --production

COPY --from=builder /app/dist ./dist

EXPOSE 8000

CMD ["node", "dist/app.js"]
