FROM node:18-alpine As builder

WORKDIR /app

COPY package.json package-lock.json ./
RUN npm install

COPY . .

RUN npm run build:prod

FROM node:18-alpine as runner

WORKDIR /app

COPY --from=builder /app/package.json /app/package-lock.json ./
RUN npm install

COPY --from=builder /app/dist ./dist

EXPOSE 8080

CMD ["node", "dist/src/app.js"]
