name: Integration continue backend node-express
on: push

jobs:
  check-backend:
    name: Check du code source back

    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./backend

    steps:
      - uses: actions/checkout@v2

      - name: install packages
        run: npm install

      - name: lint, type-check, test
        run: |
          npm run format
          npm run lint
          npm run type-check
          # ignoring temporarily model tests that require access to mongo database
          npm run test -- --testPathIgnorePatterns "/src/tests/models"
