name: Integration continue frontend next
on: push

jobs:
  check-frontend:
    name: Check du code source front
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./frontend
    steps:
      - uses: actions/checkout@v2

      - name: install packages
        run: npm install

      - name: lint, type-check, test
        run: npm run test-all
