name: Integration continue backend node-express
on: push

jobs:
  check-backend:
    name: Check du code source back

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Build et push Docker images
        run: |
          docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_TOKEN }}
          docker-compose -f ./docker-compose.yml build
          docker-compose -f ./docker-compose.yml push

      - name: Lancer les conteneurs
        run: |
          docker-compose -f ./docker-compose.yml up -d
          sleep 10

      - name: Install packages et run tests
        run: |
          cd ./backend
          npm install
          npm run test-all

      - name: Détruire les conteneurs
        run: docker-compose -f ./docker-compose.yml down
